universe = docker
docker_image = ghcr.io/jbris/stan-docker:latest

executable = fit_test.sh
arguments = $(f) $(ni) $(nj) $(icc) $(sigma) $(gb)

output = /home/mhuang233/cv_test/test_fold_$(f)_ni_$(ni)_nj_$(nj)_icc_$(icc)_sigma_$(sigma).out
log = /home/mhuang233/cv_test/test_fold_$(f)_ni_$(ni)_nj_$(nj)_icc_$(icc)_sigma_$(sigma).log
error = /home/mhuang233/cv_test/test_fold_$(f)_ni_$(ni)_nj_$(nj)_icc_$(icc)_sigma_$(sigma).err

should_transfer_files = YES
when_to_transfer_output = ON_EXIT
transfer_input_files = fit_test.R, study3_fit.txt, cv_ni_$(ni)_nj_$(nj)_icc_$(icc)_sigma_$(sigma).RData

# IMPORTANT! Require execute servers that can access /staging
Requirements = (Target.HasCHTCStaging == true)

request_cpus = 4
request_memory = 10GB
request_disk = 2GB

queue f, ni, nj, icc, sigma from study3.txt